<?php
declare(strict_types=1);

return [
    'diagnosisPriceCents' => 1990,
    'diagnosisLabel' => 'Diagnose & Funktionsprüfung',
    'models' => [
        'dualsense' => [
            'label' => 'PS5 DualSense',
            'shortLabel' => 'DualSense',
            'description' => 'Standard-Controller der PlayStation 5',
        ],
        'dualsense-edge' => [
            'label' => 'PS5 DualSense Edge',
            'shortLabel' => 'DualSense Edge',
            'description' => 'DualSense-Edge-Controller der PlayStation 5',
        ],
    ],
    'issues' => [
        'stick-left' => [
            'label' => 'Linker Stick driftet oder reagiert falsch',
            'shortLabel' => 'Linker Stick',
            'zone' => 'stick-left',
        ],
        'stick-right' => [
            'label' => 'Rechter Stick driftet oder reagiert falsch',
            'shortLabel' => 'Rechter Stick',
            'zone' => 'stick-right',
        ],
        'buttons' => [
            'label' => 'Tasten klemmen oder reagieren nicht',
            'shortLabel' => 'Tasten',
            'zone' => 'buttons',
        ],
        'dpad' => [
            'label' => 'Steuerkreuz reagiert fehlerhaft',
            'shortLabel' => 'Steuerkreuz',
            'zone' => 'dpad',
        ],
        'triggers' => [
            'label' => 'Trigger oder Schultertasten sind auffällig',
            'shortLabel' => 'Trigger / Schultertasten',
            'zone' => 'triggers',
        ],
        'charging' => [
            'label' => 'Laden oder USB-C-Anschluss funktioniert nicht',
            'shortLabel' => 'Laden / USB-C',
            'zone' => 'charging',
        ],
        'battery' => [
            'label' => 'Akku hält nicht mehr oder lädt schlecht',
            'shortLabel' => 'Akku',
            'zone' => 'battery',
        ],
        'connection' => [
            'label' => 'Verbindung oder Anmeldung schlägt fehl',
            'shortLabel' => 'Verbindung',
            'zone' => 'connection',
        ],
        'housing' => [
            'label' => 'Gehäuse, Sturz- oder mechanischer Schaden',
            'shortLabel' => 'Gehäuse / Sturzschaden',
            'zone' => 'housing',
        ],
        'liquid' => [
            'label' => 'Flüssigkeit ist in den Controller gelangt',
            'shortLabel' => 'Flüssigkeitsschaden',
            'zone' => 'housing',
        ],
        'other' => [
            'label' => 'Anderes oder noch unklareres Fehlerbild',
            'shortLabel' => 'Anderes Fehlerbild',
            'zone' => 'connection',
        ],
    ],
    'offers' => [
        'stick-standard-one' => [
            'label' => 'Standard-Stick ersetzen – eine Seite',
            'shortLabel' => '1 Standard-Stick inkl. Kalibrierung',
            'description' => 'Ein verschlissenes Analogstick-Modul ersetzen, kalibrieren und vollständig testen.',
            'priceCents' => 4490,
            'models' => ['dualsense'],
            'zone' => 'stick-left',
            'group' => 'stick-solution',
            'badge' => 'Reparatur',
        ],
        'stick-standard-two' => [
            'label' => 'Standard-Sticks ersetzen – beide Seiten',
            'shortLabel' => '2 Standard-Sticks inkl. Kalibrierung',
            'description' => 'Beide Analogstick-Module gemeinsam ersetzen, kalibrieren und testen.',
            'priceCents' => 6990,
            'models' => ['dualsense'],
            'zone' => 'sticks',
            'group' => 'stick-solution',
            'badge' => 'Paket',
        ],
        'hall-pair' => [
            'label' => 'Hall-Effect-Umbau – zwei Sticks',
            'shortLabel' => 'Hall-Effect-Umbau (2 Sticks)',
            'description' => 'Zwei kontaktlos arbeitende Hall-Effect-Sticks inklusive Einbau, digitaler Kalibrierung und Funktionstest.',
            'priceCents' => 9990,
            'models' => ['dualsense'],
            'zone' => 'sticks',
            'group' => 'stick-solution',
            'badge' => 'Beliebt',
        ],
        'battery-upgrade' => [
            'label' => 'Akku-Upgrade 2.600 mAh',
            'shortLabel' => 'Akku-Upgrade 2.600 mAh',
            'description' => 'Kapazitätsstärkeren Akku einbauen und Lade- sowie Funktionstest durchführen.',
            'priceCents' => 5490,
            'models' => ['dualsense'],
            'zone' => 'battery',
            'group' => 'battery-solution',
            'badge' => 'Upgrade',
        ],
        'cleaning' => [
            'label' => 'Innenreinigung & Wartung',
            'shortLabel' => 'Innenreinigung & Wartung',
            'description' => 'Controller öffnen, innen reinigen, auffällige Mechanik prüfen und abschließend testen.',
            'priceCents' => 3490,
            'models' => ['dualsense', 'dualsense-edge'],
            'zone' => 'housing',
            'group' => 'cleaning',
            'badge' => 'Pflege',
        ],
        'face-clicky' => [
            'label' => 'Clicky-Tasten – D-Pad & Aktionstasten',
            'shortLabel' => 'Clicky-Tasten',
            'description' => 'Kurzes, taktiles Klickgefühl für Steuerkreuz und Aktionstasten, passend zur verbauten Controller-Revision.',
            'priceCents' => 4990,
            'models' => ['dualsense'],
            'zone' => 'buttons',
            'group' => 'clicky-solution',
            'badge' => 'Performance',
        ],
        'trigger-clicky' => [
            'label' => 'Clicky-Trigger – L1/L2 & R1/R2',
            'shortLabel' => 'Clicky-Trigger',
            'description' => 'Kurzer digitaler Auslöseweg für Shooter; adaptive Triggerfunktion wird dabei bewusst ersetzt.',
            'priceCents' => 5490,
            'models' => ['dualsense'],
            'zone' => 'triggers',
            'group' => 'clicky-solution',
            'badge' => 'Shooter',
        ],
        'full-clicky' => [
            'label' => 'Full-Clicky-Paket',
            'shortLabel' => 'Full-Clicky-Paket',
            'description' => 'Clicky-Tasten und Clicky-Trigger gemeinsam einbauen – günstiger als zwei einzelne Umbauten.',
            'priceCents' => 7990,
            'models' => ['dualsense'],
            'zone' => 'clicky-full',
            'group' => 'clicky-solution',
            'badge' => 'Bundle',
        ],
        'back-paddles' => [
            'label' => 'Back-Paddle-Umbau',
            'shortLabel' => 'Back-Paddle-Umbau',
            'description' => 'Programmierbare Rücktasten mit passendem Rückgehäuse; Ausführung nach Controller-Revision.',
            'priceCents' => 9990,
            'models' => ['dualsense'],
            'zone' => 'back-paddles',
            'group' => 'paddle-solution',
            'badge' => 'Pro',
        ],
        'back-paddles-metal' => [
            'label' => 'Back-Paddle Pro – Metalltasten',
            'shortLabel' => 'Back-Paddle Pro mit Metalltasten',
            'description' => 'Vier programmierbare Rücktasten mit Metall-Bedienelementen und passendem Rückgehäuse.',
            'priceCents' => 11990,
            'models' => ['dualsense'],
            'zone' => 'back-paddles',
            'group' => 'paddle-solution',
            'badge' => 'Premium',
        ],
        'back-paddles-oled' => [
            'label' => 'Back-Paddle OLED-Paket',
            'shortLabel' => 'Back-Paddle OLED-Paket',
            'description' => 'Vier Rücktasten, Display, Trigger-Stops und ergonomisches Rückgehäuse als Komplettumbau.',
            'priceCents' => 12990,
            'models' => ['dualsense'],
            'zone' => 'back-paddles',
            'group' => 'paddle-solution',
            'badge' => 'Top-Ausstattung',
        ],
        'led-kit' => [
            'label' => 'LED-Beleuchtungs-Umbau',
            'shortLabel' => 'LED-Beleuchtungs-Umbau',
            'description' => 'Mehrfarbige Beleuchtung inklusive sauberer Verlegung, Einbau und Funktionstest.',
            'priceCents' => 9990,
            'models' => ['dualsense'],
            'zone' => 'led',
            'group' => 'lighting',
            'badge' => 'Style',
        ],
        'edge-face-clicky' => [
            'label' => 'Edge Clicky-Tasten',
            'shortLabel' => 'Edge Clicky-Tasten',
            'description' => 'Taktiles Klickgefühl für Steuerkreuz und Aktionstasten des DualSense Edge.',
            'priceCents' => 5990,
            'models' => ['dualsense-edge'],
            'zone' => 'buttons',
            'group' => 'edge-clicky',
            'badge' => 'Performance',
        ],
        'edge-beyond-paddles' => [
            'label' => 'Edge Back-Paddle OLED-Paket',
            'shortLabel' => 'Edge Back-Paddle OLED-Paket',
            'description' => 'Ergonomisches Rückgehäuse mit zusätzlichen Rücktasten und Display für den DualSense Edge.',
            'priceCents' => 11990,
            'models' => ['dualsense-edge'],
            'zone' => 'back-paddles',
            'group' => 'edge-paddle-upgrade',
            'badge' => 'Edge Upgrade',
        ],
        'edge-magnetic-module' => [
            'label' => 'Edge Rücktasten-Magnetmodule reparieren',
            'shortLabel' => 'Edge Magnetmodule Rücktasten',
            'description' => 'Lockere oder verschlissene magnetische Aufnahmen der Edge-Rücktasten ersetzen.',
            'priceCents' => 4990,
            'models' => ['dualsense-edge'],
            'zone' => 'back-paddles',
            'group' => 'edge-back-repair',
            'badge' => 'Reparatur',
        ],
        'edge-switch-board' => [
            'label' => 'Edge Rücktasten-Schalterplatine reparieren',
            'shortLabel' => 'Edge Schalterplatine Rücktasten',
            'description' => 'Unzuverlässige oder nicht reagierende Rücktasten durch Austausch der Schalterplatine instand setzen.',
            'priceCents' => 5490,
            'models' => ['dualsense-edge'],
            'zone' => 'back-paddles',
            'group' => 'edge-back-repair',
            'badge' => 'Reparatur',
        ],
    ],
    'extras' => [
        'opened-before' => [
            'label' => 'Controller wurde bereits geöffnet oder repariert',
            'shortLabel' => 'Bereits geöffnet / repariert',
        ],
    ],
];
