<?php
declare(strict_types=1);

return [
    'models' => [
        'dualsense' => [
            'label' => 'PS5 DualSense',
            'shortLabel' => 'DualSense',
            'description' => 'Standard-Controller der PlayStation 5',
        ],
        'dualsense-edge' => [
            'label' => 'PS5 DualSense Edge',
            'shortLabel' => 'DualSense Edge',
            'description' => 'DualSense-Edge-Controller der PlayStation 5',
        ],
    ],
    'offers' => [
        'hall-pair' => [
            'label' => 'Hall-Effect-Umbau – zwei Sticks',
            'shortLabel' => 'Hall-Effect-Umbau (2 Sticks)',
            'description' => 'Zwei kontaktlos arbeitende Hall-Effect-Sticks inklusive Einbau, digitaler Kalibrierung und Funktionstest.',
            'priceCents' => 9990,
            'models' => ['dualsense'],
            'zone' => 'sticks',
            'group' => 'stick-solution',
            'badge' => 'Beliebt',
        ],
        'battery-upgrade' => [
            'label' => 'Akku-Upgrade 2.600 mAh',
            'shortLabel' => 'Akku-Upgrade 2.600 mAh',
            'description' => 'Kapazitätsstärkeren Akku einbauen und Lade- sowie Funktionstest durchführen.',
            'priceCents' => 5490,
            'models' => ['dualsense'],
            'zone' => 'battery',
            'group' => 'battery-solution',
            'badge' => 'Upgrade',
        ],
        'face-clicky' => [
            'label' => 'Clicky-Tasten – D-Pad & Aktionstasten',
            'shortLabel' => 'Clicky-Tasten',
            'description' => 'Kurzes, taktiles Klickgefühl für Steuerkreuz und Aktionstasten.',
            'priceCents' => 4990,
            'models' => ['dualsense'],
            'zone' => 'buttons',
            'group' => 'clicky-solution',
            'badge' => 'Performance',
        ],
        'trigger-clicky' => [
            'label' => 'Clicky-Trigger – L1/L2 & R1/R2',
            'shortLabel' => 'Clicky-Trigger',
            'description' => 'Kurzer digitaler Auslöseweg für Shooter; adaptive Triggerfunktion wird dabei bewusst ersetzt.',
            'priceCents' => 5490,
            'models' => ['dualsense'],
            'zone' => 'triggers',
            'group' => 'clicky-solution',
            'badge' => 'Shooter',
        ],
        'full-clicky' => [
            'label' => 'Full-Clicky-Paket',
            'shortLabel' => 'Full-Clicky-Paket',
            'description' => 'Clicky-Tasten und Clicky-Trigger gemeinsam einbauen – günstiger als zwei einzelne Umbauten.',
            'priceCents' => 7990,
            'models' => ['dualsense'],
            'zone' => 'clicky-full',
            'group' => 'clicky-solution',
            'badge' => 'Bundle',
        ],
        'back-paddles' => [
            'label' => 'Back-Paddle-Umbau',
            'shortLabel' => 'Back-Paddle-Umbau',
            'description' => 'Programmierbare Rücktasten mit passendem Rückgehäuse.',
            'priceCents' => 9990,
            'models' => ['dualsense'],
            'zone' => 'back-paddles',
            'group' => 'paddle-solution',
            'badge' => 'Pro',
        ],
        'back-paddles-metal' => [
            'label' => 'Back-Paddle Pro – Metalltasten',
            'shortLabel' => 'Back-Paddle Pro mit Metalltasten',
            'description' => 'Vier programmierbare Rücktasten mit Metall-Bedienelementen und passendem Rückgehäuse.',
            'priceCents' => 11990,
            'models' => ['dualsense'],
            'zone' => 'back-paddles',
            'group' => 'paddle-solution',
            'badge' => 'Premium',
        ],
        'back-paddles-oled' => [
            'label' => 'Back-Paddle OLED-Paket',
            'shortLabel' => 'Back-Paddle OLED-Paket',
            'description' => 'Vier Rücktasten, Display, Trigger-Stops und ergonomisches Rückgehäuse als Komplettumbau.',
            'priceCents' => 12990,
            'models' => ['dualsense'],
            'zone' => 'back-paddles',
            'group' => 'paddle-solution',
            'badge' => 'Top-Ausstattung',
        ],
        'led-kit' => [
            'label' => 'LED-Beleuchtungs-Umbau',
            'shortLabel' => 'LED-Beleuchtungs-Umbau',
            'description' => 'Mehrfarbige Beleuchtung inklusive sauberer Verlegung, Einbau und Funktionstest.',
            'priceCents' => 9990,
            'models' => ['dualsense'],
            'zone' => 'led',
            'group' => 'lighting',
            'badge' => 'Style',
        ],
        'edge-face-clicky' => [
            'label' => 'Edge Clicky-Tasten',
            'shortLabel' => 'Edge Clicky-Tasten',
            'description' => 'Taktiles Klickgefühl für Steuerkreuz und Aktionstasten des DualSense Edge.',
            'priceCents' => 5990,
            'models' => ['dualsense-edge'],
            'zone' => 'buttons',
            'group' => 'edge-clicky',
            'badge' => 'Performance',
        ],
        'edge-beyond-paddles' => [
            'label' => 'Edge Back-Paddle OLED-Paket',
            'shortLabel' => 'Edge Back-Paddle OLED-Paket',
            'description' => 'Ergonomisches Rückgehäuse mit zusätzlichen Rücktasten und Display für den DualSense Edge.',
            'priceCents' => 11990,
            'models' => ['dualsense-edge'],
            'zone' => 'back-paddles',
            'group' => 'edge-paddle-upgrade',
            'badge' => 'Edge Upgrade',
        ],
    ],
    'extras' => [
        'opened-before' => [
            'label' => 'Controller wurde bereits geöffnet oder repariert',
            'shortLabel' => 'Bereits geöffnet / repariert',
        ],
    ],
];
