<?php
declare(strict_types=1);

return [
    'models' => [
        'dualsense' => [
            'label' => 'PS5 DualSense',
            'shortLabel' => 'DualSense',
            'description' => 'Standard-Controller der PlayStation 5',
        ],
        'dualsense-edge' => [
            'label' => 'PS5 DualSense Edge',
            'shortLabel' => 'DualSense Edge',
            'description' => 'DualSense-Edge-Controller der PlayStation 5',
        ],
    ],
    'sources' => [
        'customer-dropoff' => [
            'label' => 'Eigenen Controller in Telfs übergeben',
            'shortLabel' => 'Eigener Controller · Übergabe in Telfs',
            'description' => 'Sie bringen Ihren vorhandenen Controller nach Terminvereinbarung persönlich vorbei.',
            'priceCents' => [
                'dualsense' => 0,
                'dualsense-edge' => 0,
            ],
        ],
        'customer-shipping' => [
            'label' => 'Eigenen Controller einsenden',
            'shortLabel' => 'Eigener Controller · Versand',
            'description' => 'Sie senden Ihren vorhandenen Controller gut verpackt ein. Hin- und Rückversand sind nicht im Paketpreis enthalten.',
            'priceCents' => [
                'dualsense' => 0,
                'dualsense-edge' => 0,
            ],
        ],
        'new-controller' => [
            'label' => 'Neuen Controller mitbestellen',
            'shortLabel' => 'Neuer Controller durch IT-Tabelander',
            'description' => 'IT-Tabelander besorgt einen neuen Original-Controller und führt die gewählten Umbauten daran aus.',
            // Offizielle PlayStation-Direct-Preise Österreich, geprüft am 21.08.2026.
            'priceCents' => [
                'dualsense' => 7499,
                'dualsense-edge' => 21999,
            ],
        ],
    ],
    'shells' => [
        'original' => [
            'label' => 'Originalgehäuse behalten',
            'shortLabel' => 'Originalgehäuse',
            'description' => 'Keine optische Gehäuseänderung.',
            'priceCents' => 0,
            'models' => ['dualsense', 'dualsense-edge'],
            'visual' => 'original',
            'color' => '#f5f5f2',
        ],
        'dualsense-black' => [
            'label' => 'DualSense Front-Shell · Schwarz',
            'shortLabel' => 'Front-Shell Schwarz',
            'description' => 'Schwarze Front-Shell mit Touchpad-Abdeckung inklusive Einbau.',
            'priceCents' => 4990,
            'models' => ['dualsense'],
            'visual' => 'solid',
            'color' => '#16191f',
        ],
        'dualsense-green' => [
            'label' => 'DualSense Front-Shell · Grün',
            'shortLabel' => 'Front-Shell Grün',
            'description' => 'Grüne Front-Shell mit Touchpad-Abdeckung inklusive Einbau.',
            'priceCents' => 4990,
            'models' => ['dualsense'],
            'visual' => 'solid',
            'color' => '#3f765d',
        ],
        'dualsense-clear-blue' => [
            'label' => 'DualSense Front-Shell · Transparent Blau',
            'shortLabel' => 'Front-Shell Transparent Blau',
            'description' => 'Transparent-blaue Front-Shell mit Touchpad-Abdeckung inklusive Einbau.',
            'priceCents' => 5490,
            'models' => ['dualsense'],
            'visual' => 'clear',
            'color' => '#2a8fba',
        ],
        'dualsense-clear-black' => [
            'label' => 'DualSense Front-Shell · Transparent Schwarz',
            'shortLabel' => 'Front-Shell Transparent Schwarz',
            'description' => 'Transparent-schwarze Front-Shell mit Touchpad-Abdeckung inklusive Einbau.',
            'priceCents' => 5490,
            'models' => ['dualsense'],
            'visual' => 'clear',
            'color' => '#353a43',
        ],
        'edge-black' => [
            'label' => 'DualSense Edge Full-Shell · Schwarz',
            'shortLabel' => 'Edge Full-Shell Schwarz',
            'description' => 'Komplettes schwarzes Edge-Gehäuseset inklusive Einbau.',
            'priceCents' => 6990,
            'models' => ['dualsense-edge'],
            'visual' => 'solid',
            'color' => '#111318',
        ],
        'edge-orange' => [
            'label' => 'DualSense Edge Full-Shell · Orange',
            'shortLabel' => 'Edge Full-Shell Orange',
            'description' => 'Komplettes oranges Edge-Gehäuseset inklusive Einbau.',
            'priceCents' => 6990,
            'models' => ['dualsense-edge'],
            'visual' => 'solid',
            'color' => '#e05b25',
        ],
        'edge-clear' => [
            'label' => 'DualSense Edge Full-Shell · Transparent',
            'shortLabel' => 'Edge Full-Shell Transparent',
            'description' => 'Komplettes transparentes Edge-Gehäuseset inklusive Einbau.',
            'priceCents' => 6990,
            'models' => ['dualsense-edge'],
            'visual' => 'clear',
            'color' => '#aeb8c2',
        ],
    ],
    'offers' => [
        'hall-pair' => [
            'label' => 'Hall-Effect-Umbau – 80 gf Smooth',
            'shortLabel' => 'Hall-Effect 80 gf (2 Sticks)',
            'description' => 'Zwei leichtgängige 80-gf-Hall-Effect-Sticks inklusive Einbau, digitaler Kalibrierung und Funktionstest.',
            'priceCents' => 9990,
            'models' => ['dualsense'],
            'zone' => 'sticks',
            'group' => 'stick-solution',
            'badge' => 'Smooth',
        ],
        'hall-pair-120' => [
            'label' => 'Hall-Effect-Umbau – 120 gf Original Feel',
            'shortLabel' => 'Hall-Effect 120 gf (2 Sticks)',
            'description' => 'Zwei 120-gf-Hall-Effect-Sticks mit Widerstand nahe am Original inklusive Einbau, digitaler Kalibrierung und Funktionstest.',
            'priceCents' => 9990,
            'models' => ['dualsense'],
            'zone' => 'sticks',
            'group' => 'stick-solution',
            'badge' => 'Original Feel',
        ],
        'battery-upgrade' => [
            'label' => 'Akku-Upgrade 2.600 mAh',
            'shortLabel' => 'Akku-Upgrade 2.600 mAh',
            'description' => 'Kapazitätsstärkeren Akku einbauen und Lade- sowie Funktionstest durchführen.',
            'priceCents' => 5490,
            'models' => ['dualsense'],
            'zone' => 'battery',
            'group' => 'battery-solution',
            'badge' => 'Upgrade',
        ],
        'face-clicky' => [
            'label' => 'Clicky-Tasten – D-Pad & Aktionstasten',
            'shortLabel' => 'Clicky-Tasten',
            'description' => 'Kurzes, taktiles Klickgefühl für Steuerkreuz und Aktionstasten.',
            'priceCents' => 4990,
            'models' => ['dualsense'],
            'zone' => 'buttons',
            'group' => 'clicky-solution',
            'badge' => 'Performance',
        ],
        'trigger-clicky' => [
            'label' => 'Clicky-Trigger – L1/L2 & R1/R2',
            'shortLabel' => 'Clicky-Trigger',
            'description' => 'Kurzer digitaler Auslöseweg für Shooter; adaptive Triggerfunktion wird dabei bewusst ersetzt.',
            'priceCents' => 5490,
            'models' => ['dualsense'],
            'zone' => 'triggers',
            'group' => 'clicky-solution',
            'badge' => 'Shooter',
        ],
        'full-clicky' => [
            'label' => 'Full-Clicky-Paket',
            'shortLabel' => 'Full-Clicky-Paket',
            'description' => 'Clicky-Tasten und Clicky-Trigger gemeinsam einbauen – günstiger als zwei einzelne Umbauten.',
            'priceCents' => 7990,
            'models' => ['dualsense'],
            'zone' => 'clicky-full',
            'group' => 'clicky-solution',
            'badge' => 'Bundle',
        ],
        'back-paddles' => [
            'label' => 'Back-Paddle-Umbau',
            'shortLabel' => 'Back-Paddle-Umbau',
            'description' => 'Programmierbare Rücktasten mit passendem Rückgehäuse.',
            'priceCents' => 9990,
            'models' => ['dualsense'],
            'zone' => 'back-paddles',
            'group' => 'paddle-solution',
            'badge' => 'Pro',
        ],
        'back-paddles-metal' => [
            'label' => 'Back-Paddle Pro – Metalltasten',
            'shortLabel' => 'Back-Paddle Pro mit Metalltasten',
            'description' => 'Vier programmierbare Rücktasten mit Metall-Bedienelementen und passendem Rückgehäuse.',
            'priceCents' => 11990,
            'models' => ['dualsense'],
            'zone' => 'back-paddles',
            'group' => 'paddle-solution',
            'badge' => 'Premium',
        ],
        'back-paddles-oled' => [
            'label' => 'Back-Paddle OLED-Paket',
            'shortLabel' => 'Back-Paddle OLED-Paket',
            'description' => 'Vier Rücktasten, Display, Trigger-Stops und ergonomisches Rückgehäuse als Komplettumbau.',
            'priceCents' => 12990,
            'models' => ['dualsense'],
            'zone' => 'back-paddles',
            'group' => 'paddle-solution',
            'badge' => 'Top-Ausstattung',
        ],
        'led-kit' => [
            'label' => 'LED-Beleuchtungs-Umbau',
            'shortLabel' => 'LED-Beleuchtungs-Umbau',
            'description' => 'Mehrfarbige Beleuchtung inklusive sauberer Verlegung, Einbau und Funktionstest.',
            'priceCents' => 9990,
            'models' => ['dualsense'],
            'zone' => 'led',
            'group' => 'lighting',
            'badge' => 'Style',
        ],
        'edge-face-clicky' => [
            'label' => 'Edge Clicky-Tasten',
            'shortLabel' => 'Edge Clicky-Tasten',
            'description' => 'Taktiles Klickgefühl für Steuerkreuz und Aktionstasten des DualSense Edge.',
            'priceCents' => 5990,
            'models' => ['dualsense-edge'],
            'zone' => 'buttons',
            'group' => 'edge-clicky',
            'badge' => 'Performance',
        ],
        'edge-beyond-paddles' => [
            'label' => 'Edge Back-Paddle OLED-Paket',
            'shortLabel' => 'Edge Back-Paddle OLED-Paket',
            'description' => 'Ergonomisches Rückgehäuse mit zusätzlichen Rücktasten und Display für den DualSense Edge.',
            'priceCents' => 11990,
            'models' => ['dualsense-edge'],
            'zone' => 'back-paddles',
            'group' => 'edge-paddle-upgrade',
            'badge' => 'Edge Upgrade',
        ],
    ],
    'extras' => [
        'opened-before' => [
            'label' => 'Controller wurde bereits geöffnet oder repariert',
            'shortLabel' => 'Bereits geöffnet / repariert',
        ],
    ],
];
