<?php
declare(strict_types=1);

return [
    'pc-reparatur-telfs' => [
        'eyebrow' => 'PC- & Laptop-Reparatur in Telfs',
        'headline' => 'Wenn der Computer streikt, braucht es zuerst eine saubere Diagnose.',
        'lead' => 'IT-Tabelander prüft PCs und Laptops in Telfs nachvollziehbar, erklärt den Befund verständlich und setzt nur sinnvolle Reparaturen oder Upgrades um.',
        'image' => 'img/services/pc-laptop-reparatur.png',
        'imageAlt' => 'PC- und Laptop-Reparatur bei IT-Tabelander in Telfs',
        'primaryCta' => 'Reparatur anfragen',
        'problemTitle' => 'Typische Fehlerbilder',
        'problems' => [
            ['title' => 'Startprobleme', 'text' => 'Der PC bleibt schwarz, startet in einer Schleife oder Windows lädt nicht mehr zuverlässig.'],
            ['title' => 'Langsames System', 'text' => 'Lange Ladezeiten, volle Datenträger oder zu wenig Arbeitsspeicher bremsen den Alltag.'],
            ['title' => 'Überhitzung & Abstürze', 'text' => 'Laute Lüfter, hohe Temperaturen, Bluescreens oder spontane Abschaltungen werden systematisch geprüft.'],
        ],
        'serviceTitle' => 'Reparatur und Verbesserung mit klarem Befund',
        'serviceLead' => 'Vor dem Teiletausch steht die Diagnose. Danach erhalten Sie eine verständliche Einschätzung zu Aufwand, Nutzen und Kostenrahmen.',
        'services' => [
            ['title' => 'Hardware-Diagnose', 'text' => 'Prüfung von Datenträger, Arbeitsspeicher, Netzteil, Kühlung und weiteren Komponenten passend zum Fehlerbild.'],
            ['title' => 'SSD- und RAM-Upgrades', 'text' => 'Gezielte Aufrüstung, wenn sie die Nutzungsdauer verlängert und im Alltag einen spürbaren Vorteil bringt.'],
            ['title' => 'Windows-Probleme', 'text' => 'Fehleranalyse, Treiber- und Updateprobleme, Systembereinigung oder eine saubere Neuinstallation nach Absprache.'],
            ['title' => 'Reinigung und Wartung', 'text' => 'Staub, Wärmeleitmaterial und Kühlung werden geprüft, wenn Temperatur oder Lautstärke auffällig sind.'],
        ],
        'audienceTitle' => 'Direkt in Telfs und in der Umgebung erreichbar',
        'audienceText' => 'Der Service richtet sich an Privatpersonen, Selbstständige und kleine Unternehmen in Telfs und Umgebung. Je nach Fehlerbild erfolgt die Hilfe vor Ort, per Fernwartung oder nach Geräteübergabe.',
        'processTitle' => 'So läuft eine Reparaturanfrage ab',
        'process' => [
            ['title' => 'Fehler kurz schildern', 'text' => 'Gerät, Symptome und Dringlichkeit übermitteln.'],
            ['title' => 'Diagnose abstimmen', 'text' => 'Übergabe oder Termin sowie der sinnvolle Prüfumfang werden vereinbart.'],
            ['title' => 'Empfehlung erhalten', 'text' => 'Sie entscheiden auf Basis des Befunds, ob repariert, aufgerüstet oder ersetzt wird.'],
        ],
        'ctaTitle' => 'PC oder Laptop in Telfs prüfen lassen',
        'ctaText' => 'Beschreiben Sie kurz das Fehlerbild. IT-Tabelander meldet sich mit dem passenden nächsten Schritt.',
    ],
    'it-betreuung-telfs' => [
        'eyebrow' => 'IT-Betreuung für Unternehmen',
        'headline' => 'Ein Ansprechpartner für Arbeitsplätze, Netzwerk, WLAN, Server und Benutzer.',
        'lead' => 'IT-Tabelander unterstützt kleine und mittlere Unternehmen in Telfs und Tirol bei laufender Betreuung, Störungen und einer nachvollziehbar dokumentierten IT-Umgebung.',
        'image' => 'img/network-it-tabelander.png',
        'imageAlt' => 'Strukturierte IT-Betreuung für Unternehmen in Telfs und Tirol',
        'primaryCta' => 'Erstgespräch anfragen',
        'problemTitle' => 'Für Betriebe ohne eigene IT-Abteilung',
        'problems' => [
            ['title' => 'Büros & Praxen', 'text' => 'Zuverlässige Arbeitsplätze, Benutzerzugänge, Drucker, Datenaustausch und sichere Grundkonfiguration.'],
            ['title' => 'Handwerk & Gewerbe', 'text' => 'Pragmatische Betreuung für Geräte, Netzwerk, branchenspezifische Anwendungen und mobile Arbeit.'],
            ['title' => 'Tourismus & kleine Teams', 'text' => 'Stabiles WLAN, getrennte Zugänge, laufende Updates und rasche Einordnung bei Störungen.'],
        ],
        'serviceTitle' => 'Laufende Betreuung statt ungeplanter Einzelmaßnahmen',
        'serviceLead' => 'Die Leistungen werden an Bestand, Risiko und tatsächlichen Betriebsbedarf angepasst – ohne unnötige Komplexität.',
        'services' => [
            ['title' => 'Störungsbehebung', 'text' => 'Probleme an Arbeitsplätzen, Diensten, Netzwerk und Zugängen werden priorisiert und nachvollziehbar gelöst.'],
            ['title' => 'Updates & Basisschutz', 'text' => 'Betriebssysteme, zentrale Komponenten, Berechtigungen und grundlegende Schutzmaßnahmen bleiben im Blick.'],
            ['title' => 'Benutzerverwaltung', 'text' => 'Eintritte, Austritte, Gruppen, Freigaben und Zugriffsrechte werden strukturiert gepflegt.'],
            ['title' => 'Dokumentation & Infrastruktur', 'text' => 'Wichtige Systeme, Netzwerkkomponenten, Zuständigkeiten und Änderungen werden verständlich dokumentiert.'],
        ],
        'audienceTitle' => 'Betreuung in Telfs, Tirol und per Fernwartung',
        'audienceText' => 'Vor-Ort-Unterstützung wird dort eingesetzt, wo sie technisch nötig ist. Analyse, Benutzerverwaltung und Nachbetreuung können je nach Aufgabe effizient per Fernwartung erfolgen.',
        'processTitle' => 'Vom Erstgespräch zur passenden Betreuung',
        'process' => [
            ['title' => 'Bestandsaufnahme', 'text' => 'Systeme, Arbeitsplätze, Netzwerk, Verantwortlichkeiten und akute Risiken werden erfasst.'],
            ['title' => 'Prioritäten festlegen', 'text' => 'Kritische Lücken, wiederkehrende Störungen und sinnvolle Verbesserungen werden gemeinsam geordnet.'],
            ['title' => 'Betreuung strukturieren', 'text' => 'Umfang, Reaktionsweg, Dokumentation und regelmäßige Aufgaben werden passend zum Betrieb vereinbart.'],
        ],
        'ctaTitle' => 'Unverbindliches Erstgespräch vereinbaren',
        'ctaText' => 'Schildern Sie kurz Ihre Unternehmensgröße und die wichtigsten IT-Themen. Danach klären wir, welche Betreuung wirklich sinnvoll ist.',
    ],
    'wlan-netzwerk-telfs' => [
        'eyebrow' => 'WLAN & Netzwerk in Telfs',
        'headline' => 'Stabiles WLAN beginnt mit Messung, Platzierung und einer sauberen Netzwerkstruktur.',
        'lead' => 'IT-Tabelander analysiert Funklöcher, langsame oder instabile Verbindungen und entwickelt eine passende Lösung für Wohnungen, Häuser und kleine Unternehmen in Telfs.',
        'image' => 'img/services/netzwerk-wlan.png',
        'imageAlt' => 'WLAN-Messung und Netzwerkoptimierung in Telfs',
        'primaryCta' => 'WLAN prüfen lassen',
        'problemTitle' => 'Kommt Ihnen das bekannt vor?',
        'problems' => [
            ['title' => 'Funklöcher', 'text' => 'In einzelnen Räumen oder Stockwerken bricht die Verbindung ab oder ist kaum nutzbar.'],
            ['title' => 'Instabile Verbindung', 'text' => 'Videokonferenzen, Streaming oder Kassensysteme verlieren sporadisch das Netzwerk.'],
            ['title' => 'Langsames WLAN', 'text' => 'Router- oder Access-Point-Platzierung, Kanalstörungen und alte Standards begrenzen die Leistung.'],
        ],
        'serviceTitle' => 'Vom Funkproblem zur belastbaren Lösung',
        'serviceLead' => 'Nicht jeder schlechte Empfang braucht mehr Repeater. Zuerst werden Umgebung, Nutzung und bestehende Technik eingeordnet.',
        'services' => [
            ['title' => 'WLAN-Messung', 'text' => 'Abdeckung, Signalqualität, Störungen und Übergänge zwischen Bereichen werden vor Ort geprüft.'],
            ['title' => 'Access Points & Platzierung', 'text' => 'Anzahl, Position und Anbindung von Access Points werden passend zu Gebäude und Nutzung geplant.'],
            ['title' => 'Netzwerkstruktur', 'text' => 'Router, Switches, Verkabelung und logische Trennung werden verständlich und wartbar aufgebaut.'],
            ['title' => 'Basissicherheit', 'text' => 'Verschlüsselung, Gastzugänge, Gerätezustand, Updates und unnötig offene Funktionen werden mitgeprüft.'],
        ],
        'audienceTitle' => 'Für private Haushalte und Unternehmen',
        'audienceText' => 'Zu Hause zählen zuverlässige Abdeckung und einfache Nutzung. In Unternehmen kommen getrennte Zugänge, planbare Kapazität, Sicherheit und Dokumentation hinzu.',
        'processTitle' => 'So wird Ihr WLAN geprüft',
        'process' => [
            ['title' => 'Situation erfassen', 'text' => 'Gebäude, Nutzung, bestehende Geräte und konkrete Problemstellen werden aufgenommen.'],
            ['title' => 'Messen & analysieren', 'text' => 'Signal, Störungen, Platzierung und Netzwerkpfade werden überprüft.'],
            ['title' => 'Gezielt verbessern', 'text' => 'Einstellungen, Positionen oder Komponenten werden nur dort angepasst, wo es messbar hilft.'],
        ],
        'ctaTitle' => 'WLAN in Telfs prüfen lassen',
        'ctaText' => 'Nennen Sie Gebäudeart, ungefähre Fläche und die auffälligen Bereiche. So lässt sich der nächste Schritt rasch einordnen.',
    ],
];
