<?php
declare(strict_types=1);

return [
    'home' => [
        'path' => '',
        'title' => 'Computerhilfe für Private in Telfs | IT-Tabelander',
        'description' => 'Persönliche Computerhilfe in Telfs: PC- und Laptop-Reparatur, WLAN zu Hause, Einrichtung, Sicherheit und Controller-Service aus einer Hand.',
        'ogImage' => 'img/hero-it-tabelander-1440.webp',
        'schemaType' => 'ProfessionalService',
        'serviceTypes' => [
            'PC- und Laptop-Reparatur',
            'PC- und Laptop-Upgrades',
            'Einrichtung und Datenumzug',
            'WLAN- und Heimnetz-Hilfe',
            'IT-Sicherheits- und Virenprüfung für private Geräte',
            'Controller- und Konsolen-Service',
        ],
        'indexable' => true,
        'changefreq' => 'weekly',
        'priority' => '1.0',
        'source' => 'private/pages/home.php',
        'preloadFonts' => true,
        'googleSiteVerification' => 'ZQiRDZwcqyQ1si_x_Wxw5NBKlLvHH0_AIsGCbK9xSrc',
    ],
    'pc-reparatur-telfs' => [
        'path' => 'pc-reparatur-telfs',
        'title' => 'PC & Laptop Reparatur Telfs | IT-Tabelander',
        'description' => 'PC- und Laptop-Reparatur in Telfs: Diagnose, SSD- und RAM-Upgrades, Hilfe bei Startproblemen, Überhitzung und Windows-Fehlern.',
        'ogImage' => 'img/services/pc-laptop-reparatur-1200.webp',
        'schemaType' => 'Service',
        'schemaName' => 'PC- und Laptop-Reparatur in Telfs',
        'serviceTypes' => ['PC-Reparatur', 'Laptop-Reparatur', 'SSD- und RAM-Upgrade', 'Windows-Fehlerbehebung'],
        'indexable' => true,
        'changefreq' => 'monthly',
        'priority' => '0.9',
        'source' => 'private/pages/service-landing.php',
        'contentSource' => 'private/landing-pages.php',
        'preloadFonts' => true,
    ],
    'controller-service-telfs' => [
        'path' => 'controller-service-telfs',
        'title' => 'PS5 Controller Reparatur Telfs | IT-Tabelander',
        'description' => 'PS5 DualSense und DualSense Edge in Telfs prüfen lassen: Stick-Drift, Tasten, Trigger, Ladeprobleme und weitere Fehler vorkonfigurieren.',
        'ogImage' => 'img/services/controller-konsolen-service-1200.webp',
        'schemaType' => 'Service',
        'schemaName' => 'PS5 DualSense Controller-Service in Telfs',
        'serviceTypes' => ['PS5 DualSense Reparatur', 'PS5 DualSense Edge Reparatur', 'Controller-Diagnose', 'Stick-Drift-Prüfung', 'Hall-Effect-Umbau', 'Controller-Back-Paddles', 'Clicky-Tasten-Umbau'],
        'indexable' => true,
        'changefreq' => 'monthly',
        'priority' => '0.9',
        'source' => 'private/pages/controller-configurator.php',
        'contentSource' => 'private/controller-config.php',
        'preloadFonts' => true,
    ],
    'it-betreuung-telfs' => [
        'path' => 'it-betreuung-telfs',
        'title' => 'IT-Betreuung für Unternehmen in Telfs & Tirol | IT-Tabelander',
        'description' => 'Laufende IT-Betreuung für kleine Unternehmen in Telfs und Tirol: Arbeitsplätze, Netzwerk, WLAN, Server, Benutzer und Dokumentation.',
        'ogImage' => 'img/network-it-tabelander-1024.webp',
        'schemaType' => 'Service',
        'schemaName' => 'IT-Betreuung für Unternehmen in Telfs und Tirol',
        'serviceTypes' => ['Laufende IT-Betreuung', 'Störungsbehebung', 'Benutzerverwaltung', 'IT-Dokumentation'],
        // Die frühere Firmen-Landingpage bleibt nur als archivierter Code erhalten.
        // Sie wird nicht mehr ausgeliefert oder in die Sitemap aufgenommen.
        'indexable' => false,
        'changefreq' => 'monthly',
        'priority' => '0.9',
        'source' => 'private/pages/service-landing.php',
        'contentSource' => 'private/landing-pages.php',
        'preloadFonts' => true,
    ],
    'wlan-netzwerk-telfs' => [
        'path' => 'wlan-netzwerk-telfs',
        'title' => 'WLAN & Netzwerk Telfs | IT-Tabelander',
        'description' => 'WLAN und Netzwerk in Telfs prüfen und verbessern: Funklöcher, instabile Verbindungen, Access Points, Netzwerkstruktur und Basissicherheit.',
        'ogImage' => 'img/services/netzwerk-wlan-1200.webp',
        'schemaType' => 'Service',
        'schemaName' => 'WLAN- und Netzwerk-Service in Telfs',
        'serviceTypes' => ['WLAN-Messung', 'WLAN-Optimierung', 'Access-Point-Planung', 'Netzwerk-Basissicherheit'],
        'indexable' => true,
        'changefreq' => 'monthly',
        'priority' => '0.9',
        'source' => 'private/pages/service-landing.php',
        'contentSource' => 'private/landing-pages.php',
        'preloadFonts' => true,
    ],
    'impressum' => [
        'path' => 'impressum.php',
        'title' => 'Impressum | IT-Tabelander',
        'description' => 'Impressum und Offenlegung von IT-Tabelander in Telfs.',
        'indexable' => true,
        'changefreq' => 'yearly',
        'priority' => '0.2',
        'source' => 'private/pages/impressum.php',
    ],
    'datenschutz' => [
        'path' => 'datenschutz.php',
        'title' => 'Datenschutz | IT-Tabelander',
        'description' => 'Datenschutzerklärung von IT-Tabelander in Telfs.',
        'indexable' => true,
        'changefreq' => 'yearly',
        'priority' => '0.2',
        'source' => 'private/pages/datenschutz.php',
    ],
    'nutzungsbedingungen' => [
        'path' => 'nutzungsbedingungen.php',
        'title' => 'Nutzungsbedingungen | IT-Tabelander',
        'description' => 'Nutzungsbedingungen und Hinweise zur Website von IT-Tabelander.',
        'indexable' => true,
        'changefreq' => 'yearly',
        'priority' => '0.2',
        'source' => 'private/pages/nutzungsbedingungen.php',
    ],
];
